listen: "127.0.0.1:8100"
upstreams:
  - address: "http://localhost:3000"
    weight: 1
blocked_headers:
  - User-Agent
  - X-Forwarded-For
blocked_params:
  - access_token
  - secret_key
masked_params:
  - password
  - ssn
  - credit_card
max_body_size: 10485760
strip_response_headers:
  - server
  - x-powered-by
connect_timeout_ms: 5000
request_timeout_ms: 30000
pool_idle_timeout_ms: 60000
pool_max_idle_per_host: 32
max_concurrent_requests: 1000
rate_limit:
  requests_per_second: 100
  burst: 50
