listen: "127.0.0.1:8100"
upstreams:
  - address: "http://localhost:3000"
    weight: 1
blocked_headers:
  - X-Debug-Token
  - X-Internal-Auth
blocked_params:
  - access_token
  - secret_key
masked_params:
  - password
  - ssn
  - credit_card
max_body_size: 10485760
strip_response_headers:
  - server
  - x-powered-by
timeouts:
  connect: 5
  request: 30
  idle: 60
pool:
  idle_timeout: 60
  max_idle_per_host: 32
max_concurrent_requests: 1000
rate_limit:
  requests_per_second: 100
  burst: 50
